# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deep-web',
                'doc_host': 'https://deepconclusions.github.io',
                'git_url': 'https://github.com/deepconclusions/deep-web',
                'lib_path': 'deep_web'},
  'syms': {'deep_web.core': {'deep_web.core.foo': ('core.html#foo', 'deep_web/core.py')}}}
