# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '',
                'doc_host': 'https://web.deepconclusions.com/',
                'git_url': 'https://github.com/deepconclusions/deepconclusions-web',
                'lib_path': 'deepconclusions_webdev'},
  'syms': {'deepconclusions_webdev.core': {'deepconclusions_webdev.core.foo': ('core.html#foo', 'deepconclusions_webdev/core.py')}}}
