project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  favicon: assets/deepconclusions-logo.png
  navbar:
    background: primary
    search: true
    right:
      - text: Home
        href: "https://deepconclusions.com/"
  sidebar:
    style: "floating"
    twitter-card:
    creator: "@juma_shafara"
    site: "@deepconclusions"

metadata-files: [nbdev.yml, sidebar.yml]
